# Generated by Django 6.0.6 on 2026-10-01 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roommembership',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_membership'),
        ),
    ]
